### PR TITLE
Verify ids to guard against SSRF

### PR DESCRIPTION
**Pull request by christopherstyles**
This update adds several methods to Client instances for verifying ids are valid. Many thanks to @woodhull for pointing out the potential issue. For more on SSRF see [this article](https://www.acunetix.com/blog/articles/server-side-request-forgery-vulnerability/).

### CODE REVIEW

**Comment by woodhull** [comment]
I _think_ this should work, assuming that there are never ngpvan ids or types with other characters in them. I'd have to read the docs very carefully to be sure.

**Comment by woodhull** [comment]
What was the rationale for this approach versus good old fashined URI escaping?

**Comment by christopherstyles** [comment]
The rationale was simply to reject any input that wasn’t a valid `id`, and to have a catchable/meaningful error raise when the situation occurs. 

Looking through their documentation it seems ids only have alphanumeric characters, numbers, and hyphens. This goes a step further than simply escaping by disallowing *any* crazy input. 

Is there a better case to be made for simply escaping?

**Comment by woodhull** [comment]
Nioe, sounds good

**Pull request merged**
