### PR TITLE
add an echoes endpoint, useful for testing credentials

### PR DESCRIPTION
**Pull request by anero**
Another chunk of larger https://github.com/christopherstyles/ngp_van/pull/5 PR

### CODE REVIEW

**Comment by woodhull** [comment]
Checking in on this. We're starting another round of dev and are wondering whether we should bother continuing to submit PRs or just firmly fork the library.

**Comment by christopherstyles** [comment]
Hi @woodhull! Sorry for the lag, let me take a look at this today and I’ll go ahead and get these outstanding PRs merged.

**Comment by robertsonsamuel** [comment]
Also would like to chime in here! This method would be super useful to me as well. I have a forked version for this but in the official gem would be great!

**Comment by christopherstyles** [comment]
Sure thing, this has been on my todo list for far too long. I’ll go ahead and merge and bump the version in just a sec ;) Thanks everyone!

**Pull request merged**
